import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { COMPANY_WEBSITE, COMPANY_PHONE, NOAA_LOGO_PATH, NWS_LOGO_PATH } from "./constants";
import { formatEventDate } from "./utils";
import type { SearchResult, StormEvent, SummaryStats } from "./types";

type RGB = [number, number, number];
const C: Record<string, RGB> = {
  white: [255, 255, 255], dark: [17, 24, 39], navy: [30, 58, 95],
  gray: [100, 105, 120], grayMed: [156, 163, 175], grayLight: [107, 114, 128],
  lightGray: [243, 244, 246], medGray: [209, 213, 219], zebraGray: [249, 250, 251],
  gold: [62, 143, 203], goldLight: [235, 245, 255], teal: [8, 145, 178],
  red: [220, 38, 38], amber: [245, 158, 11], green: [22, 163, 74],
  // Proximity table header colors
  greenBg: [220, 252, 231], greenText: [22, 101, 52],
  amberBg: [254, 243, 199], amberText: [146, 64, 14],
  redBg: [254, 226, 226], redText: [153, 27, 27],
  navyBg: [30, 58, 95],
  pillGrayBg: [229, 231, 235], pillGrayText: [55, 65, 81],
};
const PAD = 4;

const DISCLAIMER =
  "Data sourced from NOAA SWDI, NOAA Storm Events Database, and the National Weather Service. " +
  "This report is generated by StormSheet for informational purposes only. " +
  "This report does not constitute a roof inspection, insurance recommendation, or claim guarantee. " +
  "Final determinations are made solely by licensed insurance carriers. " +
  "This report is not an expert witness document. It is provided as-is without warranties of any kind. " +
  "No representations are made regarding accuracy or completeness. " +
  "No liability is assumed for any errors, omissions, or outcomes resulting from reliance on this report. " +
  "Users are solely responsible for use of this report and compliance with all applicable laws and regulations.";

function dSev(l: string | null): string { return l === "Minor" ? "Impacted" : l || "--"; }

function findBestClaim(events: StormEvent[]) {
  const now = new Date();
  const sorted = [...events].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  for (const e of sorted) {
    const d = Math.floor((now.getTime() - new Date(e.date).getTime()) / 864e5);
    if (d <= 365) return { event: e, tier: "claim" as const, daysRemaining: 365 - d };
    if (d <= 730) return { event: e, tier: "review" as const, daysRemaining: Math.max(0, 365 - d) };
  }
  return { event: null, tier: "none" as const, daysRemaining: 0 };
}

/** Clean radar narrative, filtering jargon */
function cleanRadar(raw: string): string {
  // Filter out forecaster jargon
  if (/as of \d+\s*(am|pm)/i.test(raw)) return "";
  if (/sounding/i.test(raw)) return "";
  if (/temperature and dewpoint/i.test(raw)) return "";
  if (/there were no storms yet/i.test(raw)) return "";
  if (/^a strong storm/i.test(raw)) return ""; // Generic NWS episode narrative, not property-specific
  if (/^unsettled weather/i.test(raw)) return ""; // Generic weather description
  const r = raw.match(/Radar[:\s]+(\w+)/i);
  const p = raw.match(/(\d+)%\s*prob/i);
  if (r && p) return `Radar: ${r[1]} — ${p[1]}% probability`;
  if (r) return `Radar: ${r[1]}`;
  return raw.length > 55 ? raw.substring(0, 55) + "..." : raw;
}

function sevColor(l: string | null): RGB {
  if (l === "Severe" || l === "Significant" || l === "Damaging" || l === "Destructive" || l === "Extreme") return C.red;
  if (l === "Moderate") return C.amber;
  return C.gray;
}

function buildProximityData(events: StormEvent[]) {
  const dateMap = new Map<string, StormEvent[]>();
  events.filter(e => e.type === "HAIL" && e.magnitude).forEach(e => {
    const dk = e.date.split("T")[0];
    if (!dateMap.has(dk)) dateMap.set(dk, []);
    dateMap.get(dk)!.push(e);
  });
  const rows: Array<{ date: string; location: string; m1: string; m2: string; m3: string; max: number }> = [];
  for (const [dk, evts] of dateMap) {
    const g = (d: number) => evts.filter(e => e.distanceFromProperty <= d).reduce((mx, e) => Math.max(mx, e.magnitude || 0), 0);
    const m1 = g(1), m2 = g(2), m3 = g(3);
    rows.push({ date: formatEventDate(dk + "T12:00:00Z"), location: evts[0].countyName || "Saline County",
      m1: m1 > 0 ? `${m1}"` : "--", m2: m2 > 0 ? `${m2}"` : "--", m3: m3 > 0 ? `${m3}"` : "--", max: Math.max(m1, m2, m3) });
  }
  return rows.sort((a, b) => b.max - a.max).slice(0, 8);
}

// =============================================
export async function generateStormReportPdf(result: SearchResult, mapElement: HTMLElement | null, customLogoBase64?: string | null): Promise<string> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const m = 12, cw = pw - m * 2;

  const [noaaLogo, nwsLogo, ssLogo] = await Promise.all([
    loadImage(NOAA_LOGO_PATH, 300).catch(() => null),
    loadImage(NWS_LOGO_PATH, 300).catch(() => null),
    loadImage("/stormsheet-logo.png", 300).catch(() => null),
  ]);

  // Use custom logo if provided, otherwise fall back to StormSheet logo
  const headerLogo = customLogoBase64 || ssLogo;

  // PAGE 1
  let y = renderHeader(doc, headerLogo, pw, m, cw);
  y = renderPropertyBoxes(doc, result, m, y, cw);
  y = renderStatsRow(doc, result, m, y, cw);
  y = renderTwoColumns(doc, result, m, y, cw);
  y = await renderStormDist(doc, result, mapElement, m, y, cw, ph);
  renderSealsP1(doc, noaaLogo, nwsLogo, m, cw, ph);
  renderFooter(doc, pw, ph, m, cw);

  // PAGE 2
  doc.addPage();
  let y2 = renderP2Header(doc, headerLogo, pw, m);
  y2 = renderReviewBox(doc, result, m, y2, cw);
  y2 = renderFullTable(doc, result, m, y2, cw, ph);
  // CTA at the BOTTOM, centered, prominent
  renderCTABottom(doc, m, cw, ph);
  doc.setPage(doc.getNumberOfPages());
  doc.setFillColor(...C.gold);
  doc.rect(m, ph - 22, cw, 1, "F");
  renderSealsP2(doc, noaaLogo, nwsLogo, m, ph);
  renderFooter(doc, pw, ph, m, cw);

  return doc.output("datauristring");
}

// =============================================
// HEADER — Logo | divider | Title RIGHT
// =============================================
function renderHeader(doc: jsPDF, logo: string | null, pw: number, m: number, cw: number): number {
  const rowY = 8, logoH = 10;
  const logoW = 42; // wider aspect ratio for the StormSheet logo
  if (logo) { try { doc.addImage(logo, "PNG", m, rowY, logoW, logoH); } catch {/**/} }
  else { doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.setTextColor(...C.dark); doc.text("STORMSHEET", m, rowY + 7); }

  // Vertical divider
  const divX = m + logoW + 4;
  doc.setDrawColor(...C.medGray); doc.setLineWidth(0.3);
  doc.line(divX, rowY + 1, divX, rowY + logoH - 1);

  // Title right of divider, vertically centered
  doc.setFont("helvetica", "bold"); doc.setFontSize(13); doc.setTextColor(...C.dark);
  doc.text("STORM DAMAGE HISTORY REPORT", divX + 5, rowY + 7);

  doc.setDrawColor(...C.medGray); doc.setLineWidth(0.3);
  doc.line(m, rowY + logoH + 3, pw - m, rowY + logoH + 3);
  return rowY + logoH + 7;
}

// =============================================
function renderPropertyBoxes(doc: jsPDF, result: SearchResult, m: number, y: number, cw: number): number {
  const gap = 4, bw = (cw - gap) / 2, bh = 34;

  doc.setFillColor(...C.lightGray); doc.roundedRect(m, y, bw, bh, 3, 3, "F");
  doc.setFont("helvetica", "normal"); doc.setFontSize(5.5); doc.setTextColor(...C.grayMed);
  doc.text("REFERENCE PROPERTY", m + PAD, y + 6);
  const parts = result.address.split(",").map(s => s.trim());
  doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...C.dark);
  doc.text((parts[0] || result.address) + ",", m + PAD, y + 12);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9);
  if (parts.length > 1) doc.text(parts.slice(1).join(", "), m + PAD, y + 17);
  doc.setFont("helvetica", "bold"); doc.setFontSize(7);
  doc.text(`${(result.countyName || "").toUpperCase()} COUNTY, ${result.state}`, m + PAD, y + 23);
  doc.setFont("helvetica", "normal"); doc.setFontSize(5.5); doc.setTextColor(...C.grayMed);
  doc.text(`Coordinates: ${result.lat.toFixed(4)}, ${result.lng.toFixed(4)}`, m + PAD, y + 28);
  doc.text("Data Sources: NOAA SWDI, NWS", m + PAD, y + 31);

  const rx = m + bw + gap;
  doc.setFillColor(...C.lightGray); doc.roundedRect(rx, y, bw, bh, 3, 3, "F");
  const cx = rx + bw / 2;
  doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(...C.gray);
  const l1 = "Federal weather records document";
  doc.text(l1, cx - doc.getTextWidth(l1) / 2, y + 9);
  doc.setFont("helvetica", "bold"); doc.setFontSize(19); doc.setTextColor(...C.dark);
  const l2 = `${result.summaryStats.totalEvents} VERIFIED SEVERE`;
  doc.text(l2, cx - doc.getTextWidth(l2) / 2, y + 17);
  const l3 = "WEATHER EVENTS";
  doc.text(l3, cx - doc.getTextWidth(l3) / 2, y + 24);
  doc.setFont("helvetica", "normal"); doc.setFontSize(8);
  const l4 = "affecting this property";
  doc.text(l4, cx - doc.getTextWidth(l4) / 2, y + 29);
  doc.setFont("helvetica", "bold");
  const l5 = "within the past 5 years";
  doc.text(l5, cx - doc.getTextWidth(l5) / 2, y + 33);

  return y + bh + PAD;
}

// =============================================
function renderStatsRow(doc: jsPDF, result: SearchResult, m: number, y: number, cw: number): number {
  const stats = result.summaryStats, bw = cw / 3, bh = 18;
  doc.setFillColor(...C.lightGray); doc.roundedRect(m, y, cw, bh, 3, 3, "F");
  const sorted = [...result.events].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  const items = [
    { v: String(stats.hailEvents), l: "HAIL EVENTS" },
    { v: String(stats.windEvents), l: stats.windEvents === 1 ? "WIND EVENT" : "WIND EVENTS" },
    { v: sorted.length > 0 ? formatEventDate(sorted[0].date) : "N/A", l: "LAST EVENT" },
  ];
  items.forEach((it, i) => {
    const bx = m + i * bw;
    if (i > 0) { doc.setDrawColor(...C.medGray); doc.setLineWidth(0.2); doc.line(bx, y + 4, bx, y + bh - 4); }
    doc.setFont("helvetica", "bold"); doc.setFontSize(15); doc.setTextColor(...C.dark);
    doc.text(it.v, bx + PAD, y + 11);
    doc.setFont("helvetica", "normal"); doc.setFontSize(5.5); doc.setTextColor(...C.grayMed);
    doc.text(it.l, bx + PAD, y + 16);
  });
  return y + bh + PAD;
}

// =============================================
function renderTwoColumns(doc: jsPDF, result: SearchResult, m: number, y: number, cw: number): number {
  const leftW = cw * 0.55, rightW = cw * 0.42, rightX = m + leftW + cw * 0.03;
  const startY = y, stats = result.summaryStats;

  // LEFT: History Summary bullets
  const bullets: string[] = [];
  const sorted = [...result.events].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  if (sorted.length > 0) bullets.push(`${formatEventDate(sorted[0].date)} represents the most recent hail activity within close proximity of the property.`);
  if (stats.clusteredStormDates.length > 0) bullets.push("Multiple hail events were recorded on the same date, indicating a sustained storm system.");
  if (stats.largestHail !== null && stats.largestHail >= 1.75) bullets.push(`Hail measuring up to ${stats.largestHail} inches has been recorded in the surrounding area.`);
  if (stats.highestWind !== null && stats.highestWind >= 55) bullets.push(`Wind activity up to ${stats.highestWind} mph has also been documented within proximity of the property.`);
  const uniqueYears = new Set(result.events.map(e => new Date(e.date).getFullYear()));
  if (uniqueYears.size >= 3) bullets.push("Repeated storm exposure has occurred over multiple years.");

  const leftBoxH = Math.max(bullets.length * 8 + 10, 68); // Taller to give DATA METHODOLOGY box room
  doc.setFillColor(...C.lightGray); doc.roundedRect(m, y, leftW, leftBoxH, 3, 3, "F");
  doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.setTextColor(...C.dark);
  doc.text("HISTORY SUMMARY", m + PAD, y + 7);
  let ly = y + 14;
  bullets.forEach(b => {
    doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.setTextColor(...C.gold);
    doc.text("v", m + PAD, ly);
    doc.setFont("helvetica", "normal"); doc.setFontSize(7.5); doc.setTextColor(...C.dark);
    const w = doc.splitTextToSize(b, leftW - PAD * 2 - 6);
    doc.text(w, m + PAD + 5, ly);
    ly += w.length * 3.5 + 2;
  });

  // RIGHT: Gauge (15% smaller)
  const isHigh = stats.urgentEvents > 0 || (stats.largestHail !== null && stats.largestHail >= 1.75);
  const isMod = stats.recentEvents > 0 || stats.totalEvents >= 5;
  const riskLevel = isHigh ? "High" : isMod ? "Elevated" : "Low";
  const riskColor = isHigh ? C.red : isMod ? C.amber : C.green;

  const gaugeBoxH = 44;
  doc.setFillColor(230, 230, 235); doc.roundedRect(rightX + 0.6, startY + 0.6, rightW, gaugeBoxH, 3, 3, "F");
  doc.setFillColor(...C.lightGray); doc.roundedRect(rightX, startY, rightW, gaugeBoxH, 3, 3, "F");

  const gx = rightX + rightW / 2, gy = startY + 16, gr = 13; // 15% smaller
  drawGauge(doc, gx, gy, gr);
  const nPct = isHigh ? 0.82 : isMod ? 0.5 : 0.18;
  const nA = Math.PI + nPct * Math.PI;
  doc.setDrawColor(...C.dark); doc.setLineWidth(1.0);
  doc.line(gx, gy, gx + Math.cos(nA) * (gr - 3), gy + Math.sin(nA) * (gr - 3));
  doc.setFillColor(...C.dark); doc.circle(gx, gy, 1.5, "F");

  doc.setFont("helvetica", "normal"); doc.setFontSize(5); doc.setTextColor(...C.grayMed);
  const rl = "RISK LEVEL"; doc.text(rl, gx - doc.getTextWidth(rl) / 2, gy + 5);
  doc.setFont("helvetica", "bold"); doc.setFontSize(13); doc.setTextColor(...riskColor);
  doc.text(riskLevel, gx - doc.getTextWidth(riskLevel) / 2, gy + 10);

  // 2x2 grid bullets below gauge
  const gridY = startY + gaugeBoxH - 12;
  const colL = rightX + PAD, colR = rightX + rightW / 2 + 2;
  const gridItems = [
    ["Hail activity", "within 2 miles"],
    ["Multiple past", "storm events"],
    ["NOAA radar-", "confirmed data"],
    ...(stats.highestWind !== null && stats.highestWind >= 55 ? [["Wind damage", "threshold exceeded"]] : [["", ""]]),
  ];
  for (let i = 0; i < Math.min(gridItems.length, 4); i++) {
    const col = i % 2 === 0 ? colL : colR;
    const row = Math.floor(i / 2);
    const gy2 = gridY + row * 5;
    if (gridItems[i][0]) {
      doc.setFont("helvetica", "bold"); doc.setFontSize(4.5); doc.setTextColor(...C.gold);
      doc.text("v", col, gy2);
      doc.setFont("helvetica", "normal"); doc.setFontSize(4.5); doc.setTextColor(...C.dark);
      doc.text(gridItems[i][0], col + 4, gy2);
      doc.text(gridItems[i][1], col + 4, gy2 + 2.5);
    }
  }

  // DATA METHODOLOGY
  const ry = startY + gaugeBoxH + 2;
  const wmH = leftBoxH - gaugeBoxH - 2;
  if (wmH > 10) {
    doc.setFillColor(...C.lightGray); doc.roundedRect(rightX, ry, rightW, wmH, 3, 3, "F");
    doc.setFont("helvetica", "bold"); doc.setFontSize(6.5); doc.setTextColor(...C.dark);
    doc.text("DATA METHODOLOGY", rightX + PAD, ry + 5);
    doc.setFont("helvetica", "normal"); doc.setFontSize(6); doc.setTextColor(...C.grayLight);
    doc.text(doc.splitTextToSize("Based on recent storm activity, this property falls within a standard insurance evaluation window. A professional roof inspection is recommended to assess potential damage before the window closes.", rightW - PAD * 2), rightX + PAD, ry + 10);
  }

  return startY + leftBoxH + PAD;
}

// =============================================
async function renderStormDist(doc: jsPDF, result: SearchResult, mapElement: HTMLElement | null, m: number, y: number, cw: number, ph: number): Promise<number> {
  if (y > ph - 80) return y;
  doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.setTextColor(...C.dark);
  doc.text("STORM EVENT DISTRIBUTION ", m, y + 3);
  const bw = doc.getTextWidth("STORM EVENT DISTRIBUTION ");
  doc.setFont("helvetica", "normal"); doc.text("(LAST 5 YEARS)", m + bw, y + 3);
  y += 7;

  const leftW = cw * 0.48, rightW = cw * 0.49, rightX = m + leftW + cw * 0.03;
  const mapH = 38;

  // Map
  if (mapElement) {
    try {
      const canvas = await html2canvas(mapElement, { useCORS: true, scale: 2, backgroundColor: "#1a1d27" });
      doc.addImage(canvas.toDataURL("image/jpeg", 0.8), "JPEG", m, y, leftW, mapH);
      doc.setDrawColor(...C.medGray); doc.setLineWidth(0.3); doc.roundedRect(m, y, leftW, mapH, 2, 2, "S");
    } catch { doc.setFillColor(...C.lightGray); doc.roundedRect(m, y, leftW, mapH, 2, 2, "F"); }
  } else { doc.setFillColor(...C.lightGray); doc.roundedRect(m, y, leftW, mapH, 2, 2, "F"); doc.setFontSize(7); doc.setTextColor(...C.gray); doc.text("Map unavailable", m + leftW / 2 - 10, y + mapH / 2); }

  // Proximity table below map with colored headers
  let py = y + mapH + 3;
  doc.setFont("helvetica", "bold"); doc.setFontSize(5); doc.setTextColor(...C.dark);
  doc.text("HAIL STORM EVENTS — ESTIMATED SIZE AND PROXIMITY", m, py);
  py += 3;

  const proxData = buildProximityData(result.events);
  const tblW = leftW;
  const dateW = tblW * 0.25, locW = tblW * 0.30, distW = (tblW - dateW - locW) / 3;
  const pc = { date: m, loc: m + dateW, m1: m + dateW + locW, m2: m + dateW + locW + distW, m3: m + dateW + locW + distW * 2 };

  // Table border
  doc.setDrawColor(...C.medGray); doc.setLineWidth(0.3);

  // Header row
  const hh = 4;
  doc.setFillColor(...C.navyBg); doc.rect(pc.date, py, dateW, hh, "F"); doc.rect(pc.loc, py, locW, hh, "F");
  doc.setFillColor(...C.greenBg); doc.rect(pc.m1, py, distW, hh, "F");
  doc.setFillColor(...C.amberBg); doc.rect(pc.m2, py, distW, hh, "F");
  doc.setFillColor(...C.redBg); doc.rect(pc.m3, py, distW, hh, "F");

  doc.setFontSize(4.5); doc.setFont("helvetica", "bold");
  doc.setTextColor(...C.white); doc.text("Date", pc.date + 1, py + 2.8); doc.text("Location", pc.loc + 1, py + 2.8);
  doc.setTextColor(...C.greenText); doc.text("1 Mile", pc.m1 + 1, py + 2.8);
  doc.setTextColor(...C.amberText); doc.text("2 Miles", pc.m2 + 1, py + 2.8);
  doc.setTextColor(...C.redText); doc.text("3 Miles", pc.m3 + 1, py + 2.8);
  py += hh;

  proxData.forEach((row, idx) => {
    if (idx % 2 === 1) { doc.setFillColor(...C.zebraGray); doc.rect(m, py, tblW, 3.5, "F"); }
    doc.setFont("helvetica", "normal"); doc.setFontSize(4.5); doc.setTextColor(...C.dark);
    doc.text(row.date, pc.date + 1, py + 2.5);
    doc.text(row.location, pc.loc + 1, py + 2.5);
    doc.setFont("helvetica", "bold");
    doc.text(row.m1, pc.m1 + 1, py + 2.5);
    doc.text(row.m2, pc.m2 + 1, py + 2.5);
    doc.text(row.m3, pc.m3 + 1, py + 2.5);
    // Style "--" as gray italic
    if (row.m1 === "--") { doc.setFont("helvetica", "italic"); doc.setTextColor(...C.grayMed); doc.text("--", pc.m1 + 1, py + 2.5); }
    if (row.m2 === "--") { doc.setFont("helvetica", "italic"); doc.setTextColor(...C.grayMed); doc.text("--", pc.m2 + 1, py + 2.5); }
    if (row.m3 === "--") { doc.setFont("helvetica", "italic"); doc.setTextColor(...C.grayMed); doc.text("--", pc.m3 + 1, py + 2.5); }
    py += 3.5;
  });

  // Table border
  doc.setDrawColor(...C.medGray); doc.roundedRect(m, y + mapH + 6, tblW, py - (y + mapH + 6), 1, 1, "S");

  py += 1;
  doc.setFont("helvetica", "italic"); doc.setFontSize(3.5); doc.setTextColor(...C.grayMed);
  doc.text("Hail size values represent estimated maximum diameter within specified distances from the property.", m, py);
  py += 2;
  doc.text("Storm activity assessed based on proximity and meteorological relevance to the subject property.", m, py);

  // RIGHT: Abbreviated event table — tight columns
  const tc = {
    date: rightX,
    type: rightX + rightW * 0.28,
    mag: rightX + rightW * 0.42,
    dist: rightX + rightW * 0.58,
    sev: rightX + rightW * 0.72,
  };

  doc.setFont("helvetica", "bold"); doc.setFontSize(5); doc.setTextColor(...C.gray);
  doc.text("Date", tc.date, y + 3); doc.text("Type", tc.type, y + 3);
  doc.text("Mag.", tc.mag, y + 3); doc.text("Dist.", tc.dist, y + 3); doc.text("Severity", tc.sev, y + 3);
  doc.setDrawColor(...C.medGray); doc.line(rightX, y + 4.5, rightX + rightW, y + 4.5);

  let ty = y + 8;
  result.events.slice(0, 10).forEach((ev, idx) => {
    if (idx % 2 === 0) { doc.setFillColor(...C.zebraGray); doc.rect(rightX, ty - 2, rightW, 4.5, "F"); }
    doc.setFont("helvetica", "normal"); doc.setFontSize(5); doc.setTextColor(...C.dark);
    doc.text(formatEventDate(ev.date), tc.date, ty);
    doc.text(ev.type, tc.type, ty);
    doc.setFont("helvetica", "bold");
    doc.text(ev.magnitude ? `${ev.magnitude}${ev.magnitudeUnit === "inches" ? '"' : " mph"}` : "--", tc.mag, ty);
    doc.setFont("helvetica", "normal");
    doc.text(`${ev.distanceFromProperty.toFixed(1)} mi`, tc.dist, ty);
    doc.setTextColor(...sevColor(ev.severityLabel)); doc.setFont("helvetica", "bold");
    doc.text(dSev(ev.severityLabel), tc.sev, ty);
    ty += 4.5;
  });

  return Math.max(py + 3, ty + 2);
}

// =============================================
function renderSealsP1(doc: jsPDF, noaa: string | null, nws: string | null, m: number, cw: number, ph: number) {
  doc.setPage(1);
  const by = ph - 32;
  doc.setFont("helvetica", "normal"); doc.setFontSize(5); doc.setTextColor(...C.grayMed);
  const lbl = "DATA VERIFIED BY FEDERAL WEATHER AGENCIES";
  doc.text(lbl, m + cw / 2 - doc.getTextWidth(lbl) / 2, by);
  const s = 12, cx = m + cw / 2;
  if (noaa) { try { doc.addImage(noaa, "PNG", cx - 18, by + 2, s, s); } catch {/**/} }
  if (nws) { try { doc.addImage(nws, "PNG", cx + 7, by + 2, s, s); } catch {/**/} }
  doc.setFontSize(4); doc.text("NOAA", cx - 15, by + s + 4); doc.text("NWS", cx + 10, by + s + 4);
}

function renderSealsP2(doc: jsPDF, noaa: string | null, nws: string | null, m: number, ph: number) {
  doc.setPage(doc.getNumberOfPages());
  const by = ph - 18, s = 7;
  if (noaa) { try { doc.addImage(noaa, "PNG", m, by, s, s); } catch {/**/} }
  if (nws) { try { doc.addImage(nws, "PNG", m + s + 2, by, s, s); } catch {/**/} }
}

function renderFooter(doc: jsPDF, pw: number, ph: number, m: number, cw: number) {
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setDrawColor(...C.medGray); doc.setLineWidth(0.15);
    doc.line(m, ph - 10, pw - m, ph - 10);
    doc.setFontSize(3.5); doc.setFont("helvetica", "normal"); doc.setTextColor(...C.grayMed);
    const tx = p === 1 ? m : m + 18;
    doc.text(DISCLAIMER, tx, ph - 8, { maxWidth: cw * 0.85 });
    doc.setFontSize(4.5); doc.text(`Page ${p} of ${pages}`, pw - m - 14, ph - 3);
  }
}

// =============================================
// PAGE 2
// =============================================
function renderP2Header(doc: jsPDF, logo: string | null, pw: number, m: number): number {
  if (logo) { try { doc.addImage(logo, "PNG", m, 6, 34, 8); } catch {/**/} }
  doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(...C.dark);
  const t = "STORM DAMAGE HISTORY REPORT";
  doc.text(t, pw - m - doc.getTextWidth(t), 12);
  doc.setDrawColor(...C.medGray); doc.setLineWidth(0.3); doc.line(m, 17, pw - m, 17);
  return 23;
}

function renderReviewBox(doc: jsPDF, result: SearchResult, m: number, y: number, cw: number): number {
  const bcd = findBestClaim(result.events);
  const bh = 30, cx = m + cw / 2;

  doc.setFillColor(...C.goldLight); doc.roundedRect(m, y, cw, bh, 3, 3, "F");
  doc.setDrawColor(...C.gold); doc.setLineWidth(0.7); doc.roundedRect(m, y, cw, bh, 3, 3, "S");

  if (bcd.tier === "claim" && bcd.event) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...C.gold);
    const h = "YOUR BEST CLAIM DATE"; doc.text(h, cx - doc.getTextWidth(h) / 2, y + 7);
    doc.setFontSize(16); doc.setTextColor(...C.dark);
    const d = formatEventDate(bcd.event.date); doc.text(d, cx - doc.getTextWidth(d) / 2, y + 15);
    const dc = bcd.daysRemaining < 90 ? C.red : bcd.daysRemaining < 180 ? C.amber : C.gold;
    doc.setTextColor(...dc); doc.setFontSize(10); doc.setFont("helvetica", "bold");
    let dt = `${bcd.daysRemaining} DAYS REMAINING TO FILE`;
    if (bcd.daysRemaining < 90) dt = "!! " + dt + " — Filing window closing, act now";
    doc.text(dt, cx - doc.getTextWidth(dt) / 2, y + 22);
    doc.setFont("helvetica", "normal"); doc.setFontSize(6); doc.setTextColor(...C.gray);
    const sub = "A professional roof inspection is recommended before this window closes.";
    doc.text(sub, cx - doc.getTextWidth(sub) / 2, y + 27);
  } else if (bcd.tier === "review" && bcd.event) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...C.amber);
    const h = "REVIEW RECOMMENDED"; doc.text(h, cx - doc.getTextWidth(h) / 2, y + 7);
    doc.setFontSize(16); doc.setTextColor(...C.dark);
    const d = formatEventDate(bcd.event.date); doc.text(d, cx - doc.getTextWidth(d) / 2, y + 14);

    // Days remaining calculation — how many days until 365 from event
    const daysAgo = Math.floor((new Date().getTime() - new Date(bcd.event.date).getTime()) / 864e5);
    const daysLeft = 365 - daysAgo;
    if (daysLeft > 0) {
      const dc = daysLeft < 90 ? C.red : daysLeft < 180 ? C.amber : C.gold;
      doc.setTextColor(...dc); doc.setFontSize(9); doc.setFont("helvetica", "bold");
      const dt = `${daysLeft} DAYS REMAINING TO FILE`;
      doc.text(dt, cx - doc.getTextWidth(dt) / 2, y + 20);
    } else {
      doc.setTextColor(...C.amber); doc.setFontSize(8); doc.setFont("helvetica", "bold");
      const dt = "Evaluation window — contact us";
      doc.text(dt, cx - doc.getTextWidth(dt) / 2, y + 20);
    }

    doc.setFont("helvetica", "normal"); doc.setFontSize(6); doc.setTextColor(...C.gray);
    const sub = "Based on documented storm activity, a professional roof inspection is recommended.";
    doc.text(sub, cx - doc.getTextWidth(sub) / 2, y + 26);
  } else {
    doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(...C.gray);
    const h = "HISTORICAL EXPOSURE DOCUMENTED"; doc.text(h, cx - doc.getTextWidth(h) / 2, y + 10);
    doc.setFont("helvetica", "normal"); doc.setFontSize(7); doc.setTextColor(...C.dark);
    const sub = "No events fall within standard filing windows. This report documents cumulative weather exposure for professional evaluation.";
    doc.text(doc.splitTextToSize(sub, cw * 0.7), cx - (cw * 0.7) / 2, y + 18);
  }

  return y + bh + 10; // Extra spacing before Storm Event Distribution section
}

/** CTA anchored at bottom of last page, centered, prominent */
function renderCTABottom(doc: jsPDF, m: number, cw: number, ph: number): void {
  const lastPage = doc.getNumberOfPages();
  doc.setPage(lastPage);
  const ctaH = 20;
  const ctaY = ph - 24 - ctaH; // above gold bar + footer
  const ctaW = cw * 0.5;
  const ctaX = m + (cw - ctaW) / 2; // centered

  // Subtle background
  doc.setFillColor(...C.lightGray);
  doc.roundedRect(ctaX, ctaY, ctaW, ctaH, 3, 3, "F");
  doc.setDrawColor(...C.gold);
  doc.setLineWidth(0.5);
  doc.roundedRect(ctaX, ctaY, ctaW, ctaH, 3, 3, "S");

  const cx = ctaX + ctaW / 2;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.dark);
  const h1 = "FREE STORM HISTORY REPORT";
  doc.text(h1, cx - doc.getTextWidth(h1) / 2, ctaY + 6);

  doc.setFontSize(13);
  doc.setTextColor(...C.gold);
  doc.text(COMPANY_WEBSITE, cx - doc.getTextWidth(COMPANY_WEBSITE) / 2, ctaY + 13);

  doc.setFontSize(8);
  doc.setTextColor(...C.grayLight);
  doc.setFont("helvetica", "normal");
  const tagline = "Powered by NOAA federal weather data";
  doc.text(tagline, cx - doc.getTextWidth(tagline) / 2, ctaY + 18);
}

function renderFullTable(doc: jsPDF, result: SearchResult, m: number, y: number, cw: number, ph: number): number {
  // Section header — larger
  doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(...C.dark);
  doc.text("STORM EVENT DISTRIBUTION ", m, y);
  const tw2 = doc.getTextWidth("STORM EVENT DISTRIBUTION ");
  doc.setFont("helvetica", "normal"); doc.text("(5-YEAR HISTORY)", m + tw2, y);
  y += 6;

  // Thin gold accent line under section header
  doc.setDrawColor(...C.gold); doc.setLineWidth(0.5);
  doc.line(m, y, m + 50, y);
  y += 4;

  // Column positions — wider spacing for larger text
  const cols = {
    date: m + 1, type: m + cw * 0.13, mag: m + cw * 0.21,
    dist: m + cw * 0.31, sev: m + cw * 0.40, status: m + cw * 0.52, radar: m + cw * 0.63,
  };

  // Header row — dark background for contrast
  doc.setFillColor(...C.navy); doc.rect(m, y, cw, 6.5, "F");
  doc.setFont("helvetica", "bold"); doc.setFontSize(7); doc.setTextColor(...C.white);
  doc.text("Date", cols.date, y + 4.5); doc.text("Type", cols.type, y + 4.5);
  doc.text("Magnitude", cols.mag, y + 4.5); doc.text("Distance", cols.dist, y + 4.5);
  doc.text("Severity", cols.sev, y + 4.5); doc.text("Status", cols.status, y + 4.5);
  doc.text("RADAR DATA", cols.radar, y + 4.5);
  y += 8;

  // Leave room for CTA at bottom: stop table earlier
  const tableBottom = ph - 70;

  result.events.forEach((ev, idx) => {
    if (y > tableBottom) { doc.addPage(); y = 15; }

    const radarText = ev.source === "NWS" ? "NWS Official Warning"
      : ev.eventNarrative ? cleanRadar(ev.eventNarrative) : "";

    const isSE = ev.source === "STORM_EVENTS";
    const cleanedNar = isSE && ev.eventNarrative ? cleanRadar(ev.eventNarrative) : "";
    const showDetail = isSE && cleanedNar.length > 10 && !cleanedNar.startsWith("Radar:");
    const rh = showDetail ? 9 : 5.5;

    // Zebra striping
    if (idx % 2 === 0) { doc.setFillColor(...C.zebraGray); doc.rect(m, y - 2.5, cw, rh, "F"); }

    // Subtle row line
    doc.setDrawColor(230, 230, 235); doc.setLineWidth(0.1);
    doc.line(m, y + rh - 2.5, m + cw, y + rh - 2.5);

    // LARGER text — 7pt for main data (was 5.5)
    doc.setFont("helvetica", "normal"); doc.setFontSize(7); doc.setTextColor(...C.dark);
    doc.text(formatEventDate(ev.date), cols.date, y);
    doc.text(ev.type, cols.type, y);

    // Magnitude bold
    doc.setFont("helvetica", "bold");
    doc.text(ev.magnitude ? `${ev.magnitude}${ev.magnitudeUnit === "inches" ? '"' : " mph"}` : "--", cols.mag, y);

    doc.setFont("helvetica", "normal");
    doc.text(`${ev.distanceFromProperty.toFixed(1)} mi`, cols.dist, y);

    // Severity color coded
    doc.setTextColor(...sevColor(ev.severityLabel)); doc.setFont("helvetica", "bold");
    doc.text(dSev(ev.severityLabel), cols.sev, y);

    // Status color coded
    const sc = ev.urgencyStatus === "URGENT" ? C.red : ev.urgencyStatus === "RECENT" ? C.amber : C.gray;
    doc.setTextColor(...sc); doc.text(ev.urgencyStatus, cols.status, y);

    // Radar data — 6.5pt (was 5)
    doc.setFont("helvetica", "normal"); doc.setFontSize(6); doc.setTextColor(...C.grayLight);
    if (radarText) doc.text(radarText, cols.radar, y);

    y += 4.5;

    // Detail row — Storm Events only
    if (showDetail) {
      doc.setFont("helvetica", "italic"); doc.setFontSize(6); doc.setTextColor(...C.grayLight);
      doc.text(cleanedNar.length > 55 ? cleanedNar.substring(0, 55) + "..." : cleanedNar, cols.date + PAD, y);
      y += 4;
    }
  });

  return y + 2;
}

// =============================================
function drawGauge(doc: jsPDF, cx: number, cy: number, r: number) {
  [
    { s: Math.PI, e: Math.PI * 1.33, c: C.green },
    { s: Math.PI * 1.34, e: Math.PI * 1.66, c: C.amber },
    { s: Math.PI * 1.67, e: Math.PI * 2, c: C.red },
  ].forEach(({ s, e, c }) => {
    doc.setDrawColor(...c); doc.setLineWidth(4);
    for (let i = 0; i < 15; i++) {
      const a1 = s + (e - s) * (i / 15), a2 = s + (e - s) * ((i + 1) / 15);
      doc.line(cx + Math.cos(a1) * r, cy + Math.sin(a1) * r, cx + Math.cos(a2) * r, cy + Math.sin(a2) * r);
    }
  });
  doc.setLineWidth(0.3);
}

function loadImage(src: string, maxSize = 150): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      let w = img.width, h = img.height;
      if (w > maxSize || h > maxSize) { const s = maxSize / Math.max(w, h); w = Math.round(w * s); h = Math.round(h * s); }
      const canvas = document.createElement("canvas");
      canvas.width = w; canvas.height = h;
      canvas.getContext("2d")?.drawImage(img, 0, 0, w, h);
      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = reject;
    img.src = src;
  });
}
